"""上下文管理：两层预算控制 + 摘要压缩 + 压缩后恢复。"""

from aixcode.context.manager import (
    CompactCircuitBreaker,
    CompactEvent,
    ContentReplacementRecord,
    ContentReplacementState,
    FileReadRecord,
    RecoveryState,
    append_replacement_records,
    apply_tool_result_budget,
    auto_compact,
    build_compact_messages,
    build_recovery_attachment,
    clone_replacement_state,
    cleanup_tool_results,
    compute_compact_threshold,
    create_replacement_state,
    ensure_session_dir,
    extract_summary,
    load_replacement_records,
    make_persisted_preview,
    persist_tool_result,
    reconstruct_replacement_state,
    should_auto_compact,
)

__all__ = [
    "CompactCircuitBreaker",
    "CompactEvent",
    "ContentReplacementRecord",
    "ContentReplacementState",
    "FileReadRecord",
    "RecoveryState",
    "append_replacement_records",
    "apply_tool_result_budget",
    "auto_compact",
    "build_compact_messages",
    "build_recovery_attachment",
    "clone_replacement_state",
    "cleanup_tool_results",
    "compute_compact_threshold",
    "create_replacement_state",
    "ensure_session_dir",
    "extract_summary",
    "load_replacement_records",
    "make_persisted_preview",
    "persist_tool_result",
    "reconstruct_replacement_state",
    "should_auto_compact",
]
